export const TYPES = {
	Application: Symbol.for('Application'),
	LoggerService: Symbol.for('LoggerService'),
	ConfigService: Symbol.for('ConfigService'),
	ExceptionFilter: Symbol.for('ExceptionFilter'),
	DatabaseService: Symbol.for('DatabaseService'),
	TokenService: Symbol.for('TokenService'),
	TokenRepository: Symbol.for('TokenRepository'),
	UsersController: Symbol.for('UsersController'),
	UsersService: Symbol.for('UsersService'),
	UsersRepository: Symbol.for('UsersRepository'),
	ArticlesController: Symbol.for('ArticlesController'),
	ArticlesService: Symbol.for('ArticlesService'),
	ArticlesRepository: Symbol.for('ArticlesRepository'),
	TagsController: Symbol.for('TagsController'),
	TagsService: Symbol.for('TagsService'),
	TagsRepository: Symbol.for('TagsRepository'),
	QueryHelper: Symbol.for('QueryHelper'),
	ProfilesController: Symbol.for('ProfilesController'),
	ProfilesService: Symbol.for('ProfilesService'),
	ProfilesRepository: Symbol.for('ProfilesRepository'),
	CommentsController: Symbol.for('CommentsController'),
	CommentsService: Symbol.for('CommentsService'),
	CommentsRepository: Symbol.for('CommentsRepository'),
};
