export const TYPES = {
	Application: Symbol.for('Application'),
	LoggerService: Symbol.for('LoggerService'),
	ConfigService: Symbol.for('ConfigService'),
	ExceptionFilter: Symbol.for('ExceptionFilter'),
	DatabaseService: Symbol.for('DatabaseService'),
	TokenRepository: Symbol.for('TokenRepository'),
	TokenService: Symbol.for('TokenService'),
	UsersController: Symbol.for('UsersController'),
	UsersService: Symbol.for('UsersService'),
	UsersRepository: Symbol.for('UsersRepository'),
	ArticlesController: Symbol.for('ArticlesController'),
	ArticlesService: Symbol.for('ArticlesService'),
	ArticlesRepository: Symbol.for('ArticlesRepository'),
};
