export const TYPES = {
	Application: Symbol.for('Application'),
	LoggerService: Symbol.for('LoggerService'),
	ConfigService: Symbol.for('ConfigService'),
	ExceptionFilter: Symbol.for('ExceptionFilter'),
	DatabaseService: Symbol.for('DatabaseService'),
	TokenService: Symbol.for('TokenService'),
	TokenRepository: Symbol.for('TokenRepository'),
	UsersController: Symbol.for('UsersController'),
	UsersService: Symbol.for('UsersService'),
	ArticlesController: Symbol.for('ArticlesController'),
	ArticlesService: Symbol.for('ArticlesService'),
	TagsController: Symbol.for('TagsController'),
	TagsService: Symbol.for('TagsService'),
	QueryHelper: Symbol.for('QueryHelper'),
	ProfilesController: Symbol.for('ProfilesController'),
	ProfilesService: Symbol.for('ProfilesService'),
	CommentsController: Symbol.for('CommentsController'),
	CommentsService: Symbol.for('CommentsService'),
};
